export const ServiceUrls = {
  LanguageUrl: 'Language/GetAllLanguages',
  LoginUrl: 'Authentication/BackEndLogin',
  LogOutUrl: 'Authentication/LogOut',
  ResetPassword: 'Authentication/ResetPassword',
  GetCurrentUserViews: 'Privilege/GetCurrentUserViews',
  GetUserViewActionList: 'Privilege/GetUserViewActionList',
  GetUpdatedUserData: 'UserProfile/GetUpdatedUserData',
  UserList: 'User/GetUsers',
  UserById: 'User/GetUserById',
  AddUser: 'User/CreateUser',
  UpdateUser: 'User/UpdateUser',
  DeleteUser: 'User/DeleteUser',
  UpdateActivationStatus: 'User/UpdateActivationStatus',
  GetAllRoles: 'Role/GetAllRoles',
  RoleList: 'Role/GetRoles',
  RoleById: 'Role/GetRoleById',
  AddRole: 'Role/CreateRole',
  UpdateRole: 'Role/UpdateRole',
  DeleteRole: 'Role/DeleteRole',
  GetAllViews: 'Role/GetAllSystemPages',
  GetAllSystemAction: 'Lookup/GetAllSystemActions',
  GetAllInitialRequest: 'InitialRequest/GetInitialRequestList',
  ManifestList: 'Manifest/GetManifests',
  GetAllUserType: 'Lookup/GetAllUserType',
  GetItemMasterStatus: 'Lookup/GetItemMasterStatus',
  GetAllItemType: 'Lookup/GetItemType',
  GetAllCorporateInfoStatus: 'Lookup/GetAllCorporateInfoStatus',
  GetAllUserStatus: 'Lookup/GetAllUserStatus',
  GetAllPostOfficeType: 'Lookup/GetAllPostOfficeType',
  GetAllPaymentMethod: 'Lookup/GetAllPaymentMethod',
  GetAllDistributorType: 'Lookup/GetAllDistributorType',
  GetAllAdditionalServiceType: 'Lookup/GetAllAdditionalServiceType',
  GetAllShipmentType: 'Lookup/GetAllShipmentType',
  GetAllChannelType: 'Lookup/GetAllChannelType',
  GetAllDeliveryType: 'Lookup/GetAllDeliveryType',
  GetAllDeliveryDate: 'Lookup/GetAllDeliveryDate',
  GetAllDeliveryTime: 'Lookup/GetAllDeliveryTime',
  GetAllBuildingType: 'Lookup/GetAllBuildingType',
  GetAllBarcodeType: 'Lookup/GetAllBarcodeType',
  GetAllRequestType: 'Lookup/GetAllRequestType',
  GetAllGovernerate: 'Lookup/GetAllGovernerate',
  DeleteManifest: 'Manifest/DeleteManifest',
  AssignedManifestList: 'Manifest/GetAssignedManifests',
  PostOfficeList: 'PostOffice/GetPostOffice',
  GetPostOfficeById: 'PostOffice/GetPostOfficeById',
  AddPostOffice: 'PostOffice/CreatePostOffice',
  UpdatePostOffice: 'PostOffice/UpdatePostOffice',
  DeletePostOffice: 'PostOffice/DeletePostOffice',
  GetPostOfficeDDLByType: 'PostOffice/GetPostOfficeDDLByTypeAndGovernorate',
  GetPostOfficeDropDown: 'PostOffice/GetPostOfficeDropDown',
  GetCustomPostOffices: 'PostOffice/GetCustomPostOffices',
  GetCourierDDLUrl: 'User/GetCourierDDL',
  assignManifestToCourierURL: 'Manifest/AssignManifestToCourier',
  GetAllOfficeByTypeDDLURL: 'PostOffice/GetAllOfficeByTypeDDL',
  GetManifestById: 'Manifest/GetManifestById',
  ShelfList: 'Shelf/GetAllShelf',
  ShelfById: 'Shelf/GetShelfById',
  AddShelf: 'Shelf/CreateShelf',
  UpdateShelf: 'Shelf/UpdateShelf',
  DeleteShelf: 'Shelf/DeleteShelf',
  GetAllStore: 'Store/GetDropdownStores',
  AdditionalServiceList: 'AdditionalService/GetAllAdditionalServicesData',
  GetAllPackages: 'Package/GetAllPackages',
  GetStorlList: 'Store/GetStores',
  getPostOficceDropDownList: 'PostOffice/GetPostOfficeDropDown',
  GetFixedServicePriceList: 'FixedServicePrice/GetFixedServicePrices',
  GetAllZone: 'Lookup/GetAllZone',
  GetAllServiceType: 'Lookup/GetAllServiceType',
  GetDropDownWeightrangeList: 'WeightRange/GetDropDownWeightRange',
  GetPakegeSizelList: 'PackagingSize/GetPackagingSizeData',
  GetPackagingSizeDropDownList: 'PackagingSize/GetPackagingSizeDropDown',
  GetServicePackagingSizeData:
    'ServicePackagingSize/GetServicePackagingSizeData',
  DistributorList: 'Distributor/GetDistributors',
  getShiftTypeDropDown: 'ShiftType/GetShiftTypeDropDown',
  DeliveryDayRangeList: 'DeliveryDaysRange/GetDeliveryDaysRangData',
  GeUserstDropDownList: 'User/GeUserstDropDownList',
  GetOnlineUsersIdList: 'User/GetOnlineUsersIdList',
  GetAllWeightRange: 'WeightRange/GetAllWeightRange',
  GetInternalZone: 'InternalZone/GetInternalZoneData',
  DeleteInternalZone: 'InternalZone/DeleteInternalZone',
  GetShiftTypes: 'ShiftType/GetShiftTypes',
  GetAllInternalZone: 'Lookup/GetAllInternalZone',
  GetAvailableInternalZone: 'Lookup/GetAvailableInternalZone',
  AddInternalZone: 'InternalZone/CreateInternalZone',
  GetInternalZoneById: 'InternalZone/GetInternalZoneById',
  UpdateInternalZone: 'InternalZone/UpdateInternalZone',
  GetTripList: 'Trip/GetTrips',
  GetAllTransportation: 'Lookup/GetAllTransportation',
  GetUserDistributorsDDLUrl: 'User/GetDistributorsDDL',
  AddDistributor: 'Distributor/AddDistributor',
  getDistributorById: 'Distributor/GetDistributorById',
  EditDistributor: 'Distributor/EditDistributor',
  DeleteDistributor: 'Distributor/DeleteDistributor',
  AddDeliveryDayRange: 'DeliveryDaysRange/CreateDeliveryDaysRang',
  GetDeliveryDaysRangById: 'DeliveryDaysRange/GetDeliveryDaysRangById',
  GetDeliveryDaysRangeByServiceTypeAndZone:
    'DeliveryDaysRange/GetDeliveryDaysRangeByServiceTypeAndZone',
  DeleteDeliveryDayRange: 'DeliveryDaysRange/DeleteDeliveryDaysRang',
  EditDeliveryDayRange: 'DeliveryDaysRange/UpdateDeliveryDaysRang',
  UpdateWeightRange: 'WeightRange/UpdateWeightRange',
  GetWeightRangeById: 'WeightRange/GetWeightRangeById',
  AddFixedServicePrice: 'FixedServicePrice/CreateFixedServicePrice',
  GetFixedServicePriceById: 'FixedServicePrice/GetFixedServicePriceById',
  UpdateFixedServicePrice: 'FixedServicePrice/UpdateFixedServicePrice',
  DeleteFixedServicePrice: 'FixedServicePrice/DeleteFixedServicePrice',
  GetAdditionalServiceById: 'AdditionalService/GetAdditionalServiceById',
  AddAdditionalService: 'AdditionalService/CreateAdditionalService',
  UpdateAdditionalService: 'AdditionalService/UpdateAdditionalService',
  DeleteAdditionalService: 'AdditionalService/DeleteAdditionalService',
  DeleteWeightRange: 'WeightRange/DeleteWeightRange',
  AddWeightRange: 'WeightRange/CreateWeightRange',
  AddTrip: 'Trip/CreateTrip',
  EditTrip: 'Trip/UpdateTrip',
  DeleteTrip: 'Trip/DeleteTrip',
  getTripById: 'Trip/GetTripById',
  ForgetPassword: 'Authentication/ForgetPassword',
  ChangePassowrod: 'Authentication/ChangePassword',
  AddStore: 'Store/CreateStore',
  EditStore: 'Store/UpdateStore',
  GetStoreById: 'Store/GetStoreById',
  DeleteStore: 'Store/DeleteStore',
  AdditionalServiceLocalizationList:
    'AdditionalServiceLocalization/GetLocalizationList',
  UpdateAdditionalServiceLocalization:
    'AdditionalServiceLocalization/UpdateLocalization',
  PostOfficeLocalizationList: 'PostOfficeLocalization/GetLocalizationList',
  UpdatePostOfficeLocalization: 'PostOfficeLocalization/UpdateLocalization',
  AddShiftType: 'ShiftType/AddShiftType',
  GetShiftTypeById: 'ShiftType/GetShiftTypeById',
  DeleteShiftType: 'ShiftType/DeleteShiftType',
  EditShiftType: 'ShiftType/EditShiftType',
  GetServicePackagingSizeById:
    'ServicePackagingSize/GetServicePackagingSizeById',
  CreateServicePackagingSize: 'ServicePackagingSize/CreateServicePackagingSize',
  UpdateServicePackagingSize: 'ServicePackagingSize/UpdateServicePackagingSize',
  GetServicePackagingSizeCondition:
    'ServicePackagingSize/GetServicePackagingSizeCondition',
  GetPackagingByServiceTypeId:
    'ServicePackagingSize/GetServicePackagingSizeByServiceTypeId',
  CreateServicePackagingSizeCondition:
    'ServicePackagingSize/CreateServicePackagingSizeCondition',
  GetAllPackagingType: 'Lookup/GetAllPackagingType',
  GetAllAccountType: 'Lookup/GetAllAccountType',
  GetAllCountries: 'Lookup/GetAllCountry',
  GetAllGovernorate: 'Lookup/GetAllGovernerate',
  GetRequests: 'Request/GetRequests',
  GetRequestsByUserId: 'Request/GetRequestsByUserId',
  CalculateTotalPrice: 'Request/CalculateTotalPrice',
  CreateRequest: 'Request/CreateRequest',
  EditRequest: 'Request/EditRequest',
  UpdateIpsCode: 'Request/UpdateIpsCode',
  GetpackageSizeById: 'PackagingSize/GetPackagingSizeById',
  AddpackageSize: 'PackagingSize/CreatePackagingSize',
  EditpackageSize: 'PackagingSize/UpdatePackagingSize',
  GetRequestById: 'Request/GetRequestById',
  DeletepackageSize: 'PackagingSize/DeletePackagingSize',
  GetPackagingSizeLocalizationData:
    'PackageSizeLocalization/GetPackagingSizeLocalizationData',
  UpdatePackagingSizeLocalization:
    'PackageSizeLocalization/UpdatePackagingSizeLocalization',
  GetShiftTypeLocalizationData:
    'ShiftTypeLocalization/GetShiftTypeLocalizationData',
  UpdateShiftTypeLocalization:
    'ShiftTypeLocalization/UpdateShiftTypeLocalization',
  GetPageLocalizationData: 'PageLocalization/GetPageLocalizationData',
  UpdatePageLocalization: 'PageLocalization/UpdatePageLocalization',
  VerifyUserUrl: 'Authentication/CheckForgetPasswordData',
  GetUserProfile: 'UserProfile/GetUserProfile',
  UpdateUserProfile: 'UserProfile/UpdateUserProfile',
  GetRequestFileDataData: 'RequestFile/GetAllRequestFilesData',
  DeleteServicePackagingSize: 'ServicePackagingSize/DeleteServicePackagingSize',
  GetAllLookups: 'Lookup/GetAllLookups',
  GetLocalizationTypes: 'Lookup/GetLocalizationTypes',
  GetAllCurrency: 'Lookup/GetAllCurrency',

  LookupContentLocalizationList: 'Lookup/GetLookContentLocalizationList',
  UpdateLookupContentLocalizationList: 'Lookup/UpdateLookupContentLocalization',
  CreateLookupContent: 'Lookup/CreateLookupContent',
  GetParentLookupContentList: 'Lookup/GetParentLookupContentList',
  GetDeliveryRequests: 'Request/GetDeliveryRequests',
  GetInitialRequestMiniById: 'InitialRequest/GetInitialRequestMiniById',
  GetInitialRequestDetailById: 'InitialRequest/GetInitialRequestDetailById',
  ApproveConvertInitialRequestToRequest:
    'InitialRequest/ApproveConvertInitialRequestToRequest',
  RejectInitialRequest: 'InitialRequest/RejectInitialRequest',
  GetUserSupervisorDDLUrl: 'User/GetSupervisorDDL',
  AssignManifestToSupervisor: 'AssignItem/AssignManifestToSupervisor',
  getAssignInitialRequestSupervisor:
    'AssignInitialRequest/GetNotAssignInitialRequest',
  assignInitialRequestToSupervisor:
    'AssignItem/AssignInitialRequestToSupervisor',
  AssignManifestToCourier: 'AssignItem/AssignManifestToCourier',
  GetNotAssignInitialRequest: 'AssignInitialRequest/GetNotAssignInitialRequest',
  assignInitialRequestToDistributor:
    'AssignItem/AssignInitialRequestToDistributor',
  GetManifestListAssignedToCourier:
    'AssignItem/GetManifestListAssignedToCourier',
  GetServicePackagingSizeByServiceTypeId:
    'ServicePackagingSize/GetServicePackagingSizeByServiceTypeId',
  GetRequestTracking: 'RequestTracking/GetTrackingHistoryRequest',
  GetUserLocationList: 'RequestTracking/GetUserLocationList',
  GetRequestDetails: 'Request/GetRequestDetails',
  ReceiveRequests: 'Request/ReceiveRequests',
  UpdateInitialRequestMini: 'InitialRequest/UpdateInitialRequestMini',
  UpdateInitialRequestData: 'InitialRequest/UpdateInitialRequestData',
  AssignDODRequestToDistributor: 'AssignItem/AssignRequestToDistributor',
  AssignDODRequestToSupervisor: 'AssignItem/AssignRequestToSupervisor',
  GetRequestInvoicePrint: 'Request/RequestInvoicePrint',
  UploadUserProfile: 'Upload/UploadUserImage',
  UploadRequestImage: 'Upload/UploadRequestImage',
  UploadScannerRequestImage: 'Upload/UploadScannerRequestImage',
  CreateInitialRequestForCallCenter:
    'InitialRequest/CreateInitialRequestForCallCenter',
  GetAvailableRequeststoGroup: 'Request/GetAvailableRequeststoGroup',
  addGroup: 'Item/AddGroup',
  EditGroup: 'Item/EditGroup',
  addManifest: 'Item/AddManifest',
  addRunSheet: 'Item/AddRunSheet',
  GetInitialRequestData: 'InitialRequest/GetInitialRequestData',
  GetInitialRequestList: 'InitialRequest/GetInitialRequestList',
  GetItemDetailById: 'Item/GetItemDetailById',
  updateGroup: 'Item/updateGroup',
  updateManifest: 'Item/EditMainfest',
  GetAvailableMainfastPacakagesData: 'Item/GetMainfastPacakagesData',
  ReceiveManifest: 'item/ReceiveManifest',
  GetMainfastSingleView: 'Item/GetMainfastSingleView',
  GetRunSheetSingleView: 'Item/GetRunSheetSingleView',
  GetChildrenItems: 'Item/GetChildrenItems',
  TerminatePackage: 'item/TerminatePackage',
  GetPacakageRequestsData: 'item/GetPacakageRequestsData',
  AssignManifest: 'AssignItem/AssignManifest',
  UploadLocalizationImage: 'Upload/UploadLocalizationImage',
  GetUserlogData: 'UserLog/GetUserlogData',
  GetGroupRequests: 'Item/GetGroupRequests',
  GetManifestGroups: 'Item/GetManifestGroups',
  GetServiceTypeWihWeightRange: 'Request/GetServiceTypeWihWeightRange',
  GetDashboardChartData: 'Dashboard/GetDashboardChartData',
  GetPersonalInfoByFilter: 'PersonalInfo/GetPersonalInfoByFilter',
  GetDashboardShipmentsData: 'Dashboard/GetDashboardShipmentsData',
  GetAllPostOfficeExcludingUserPostOffice:
    'PostOffice/GetAllPostOfficeExcludingUserPostOffice',
  GetDashboardIncomingRequests: 'Dashboard/GetDashboardIncomingRequests',
  GetDashboardOutgoingRequests: 'Dashboard/GetDashboardOutgoingRequests',
  GetDashboardIncomingRequestsStore: 'Dashboard/GetIncomingStoreDashboardList',
  GetDashboardOutgoingRequestsStore: 'Dashboard/GetOutgoingStoreDashboardList',
  UploadRequestDeliveryFile: 'Upload/UploadRequestWebDeliveryFile',
  GetOutgoingGroupList: 'Item/GetOutgoingGroupList',
  GetIncomGroupList: 'Item/GetIncomGroupList',
  GetAvailableRequestList: 'Item/GetAvailableRequestList',
  GetPackageRequests: 'Item/GetPackageRequests',
  GetMainfastPacakagesDataToEdit: 'Item/GetMainfastPacakagesDataToEdit',
  GetDashboardPostOffices: 'Dashboard/GetDashboardPostOffices',
  GetOutgoingManifestList: 'Item/GetOutgoingManifestList',
  GetIncomManifestList: 'Item/GetIncomManifestList',
  GetAvailableGroupList: 'Item/GetAvailableGroupList',
  GetOfficeDeliverables: 'OfficeDeliverables/GetOfficeDeliverables',
  GetDoorToDoorDeliverables: 'DoorToDoorDeliverables/GetDoorToDoorDeliverables',
  DeleteItemAndChangeItemMovementStatus:
    'OfficeDeliverables/DeleteItemAndChangeItemMovementStatus',
  GetAllCorporateInfo: 'CorporateInfo/GetAllCorporateInfo',
  GetCorporateInfoById: 'CorporateInfo/GetCorporateInfoById',
  AddCorporateInfo: 'CorporateInfo/AddCorporateInfo',
  UpdateCorporateInfo: 'CorporateInfo/UpdateCorporateInfo',
  ChangeCorporateInfoStatus: 'CorporateInfo/ChangeCorporateInfoStatus',
  GetOutForDeliveryList: 'RunSheet/GetOutForDeliveryRequestsList',
  GetManualDelivery: 'RunSheet/GetManualDelivery',
  GetManualDeliveryByBarCode: 'RunSheet/GetManualDeliveryByBarCode',
  ConfirmManualDelivery: 'Item/ConfirmManualDelivery',
  PrintRunSheet: 'Item/PrintRunSheet',
  PrintManifest: 'Item/PrintManifest',
  GetDeliveryList: 'RunSheet/GetDeliveredList',
  ConfirmItemDelivery: 'RunSheet/ConfirmItemDelivery',
  ConfirmItemOutForDelivery: 'RunSheet/ConfirmItemOutForDelivery',
  UploadActionConfirmFile: 'Upload/UploadActionConfirmFile',
  GetRunSheetList: 'RunSheet/GetRunSheetList',
  GetPendingGroups: 'Item/GetPendingGroups',
  ReceivePendingGroups: 'item/ReceivePendingGroups',
  getBillOfLadingList: 'BillOfLading/GetBillOfLadingList',
  ValidateBillValue: 'BillOfLading/ValidateBillValue',
  getBillOfLadingDetails: 'BillOfLading/GetBillOfLadingDetail',
  PrintGruop: 'Item/PrintGruop',
  GetNotDeliveredReason: 'Lookup/GetNotDeliveredReason',
  addBillOfLading: 'BillOfLading/AddBillOfLading',
  AddRequestFile: 'RequestFile/AddRequestFile',
  CancelInitialRequest: 'InitialRequest/CancelInitialRequest',
  CancelRequest: 'Request/CancelRequest',
  UploadInitialRequestFile: 'Upload/UploadInitialRequestFile',
  GetBillOfLadingStatus: 'Lookup/GetBillOfLadingStatus',
  CancelInitialRequestFile: 'RequestFile/CancelInitialRequestFile',
  GenerateTemplate: 'RequestFile/GenerateTemplate',
  GetFailedRequestFile: 'RequestFile/GetFailedRequestFile',
  GetSystemTypes: 'Lookup/GetSystemTypes',
  GetPagesList: 'PageLocalization/GetPagesList',
  GetPageItemTypes: 'Lookup/GetPageItemTypes',
  GetPageItemLocalizationData: 'PageLocalization/GetPageItemLocalizationData',
  UpdatePageItemLocalization: 'PageLocalization/UpdatePageItemLocalization',
  GetAllGroupList: 'Item/GetAllGroupList',
  GetAllItemStatus: 'Lookup/GetItemStatus',
  GetPackageSingleView: 'Item/GetPackageSingleView',
  GetWebSiteLookups: 'Lookup/GetAllLookups',
  WebSiteLookupContentLocalizationList: 'Lookup/GetLookupContentPageList',
  CreateWebSiteLookupContent: 'Lookup/CreateLookupContent',
  GetWebSiteParentLookupContentList: 'Lookup/GetLookupContentBylookupId',
  UpdateWebSiteLookupContent: 'Lookup/UpdateLookupContent',
  UploadCMSRequestImage: 'Upload/UploadCMSRequestImage',
  UploadCMSScannerRequestImage: 'Upload/UploadCMSScannerRequestImage',
  GetContactUsPageList: 'ContactUs/GetContactUsPageList',
  changeContactUsStatus: 'ContactUs/ChangeContactUsStatus',
  DeleteWebSiteLookupContent: 'Lookup/DeleteLookupContent',
  CreateLangugeContent: 'Language/CreateLanguage',
  UpdateLangugeContent: 'Language/UpdateLanguage',
  GetAllLangugeList: 'Language/GetLanguages',
  GetLangugeById: 'Language/GetLanguageById',
  DeleteLanguge: 'Language/DeleteLanguage',
  GetMobilePostOfficeService: 'Lookup/GetMobilePostOfficeService',
  GetWebPostOfficeService: 'Lookup/GetWebPostOfficeService',
  GetAllPostOfficeExcludingCurrentOffice:
    'PostOffice/GetAllPostOfficeExcludingCurrentOffice',
  GetSpecialServiceAccount: 'Account/GetSpecialServiceAccount',
  VerifyAccountPinCodeAndGetSubAccount:
    'Account/VerifyAccountPinCodeAndGetSubAccount',
  GetSubAccountByAccountId: 'Account/GetSubAccountByAccountId',
  AccountList: 'Account/GetAllAccount',
  GetAccountDropDownList: 'Account/GetAccountDropDownList',
  AccountById: 'Account/GetAccountById',
  AddAccount: 'Account/CreateAccount',
  UpdateAccount: 'Account/UpdateAccount',
  DeleteAccount: 'Account/DeleteAccount',
  GetAllSubAccount: 'SubAccount/GetAllSubAccount',
  GetSubAccount: 'SubAccount/GetSubAccount',
  CreateSubAccount: 'SubAccount/CreateSubAccount',
  UpdateSubAccount: 'SubAccount/UpdateSubAccount',
  GetAllAccounts: 'Account/GetAllAccount',
  DeleteSubaccount: 'SubAccount/DeleteSubaccount',
  UpdateAccountActivationStatus: 'Account/UpdateAccountActivationStatus',
  UpdateActivationSubAccount: 'SubAccount/UpdateActivationStatus',
  GetAllPostOfficeSetting: 'PostOfficeSetting/GetAllPostOfficeSetting',

  RunSheetRequestList: 'Report/RunSheetRequest',
  MainfestRequest: 'Report/MainfestRequest',
  PendingRecieveOfficeRequest: 'Report/PendingReceiveFromAnotherOfficeRequests',
  RecieveOfficeRequest: 'Report/GetReceivedRequestsFromOffice',
  GetGroupPackagedRequestsReport: 'Report/GetGroupPackagedRequestsReport',
  ReceivedFromOperatorRequestList: 'Report/GetReceivedSheetRequest',
  PendingReceivedFromOperatorRequestList:
    'Report/GetPendingReceiveRequestsFromOperatorReport',

  GetReGroupedRequestsReport: 'Report/GetReGroupedRequestsReport',
  GetTotalShipmentReport: 'Report/GetTotalShipmentReport',

  ExportGetGroupPackagedRequestsReport:
    'Report/ExportGetGroupPackagedRequestsReport',
  ExportGetTotalShipmentReport: 'Report/ExportGetTotalShipmentReport',
  ExportGetPendingReceiveRequestsFromOperatorReport:
    'Report/ExportGetPendingReceiveRequestsFromOperatorReport',
  ExportMainfestRequest: 'Report/ExportMainfestRequest',
  RunSheetRequestExcelExport: 'Report/RunSheetRequestExcelExport',
  GetReGroupedRequestsReportExcelExport:
    'Report/GetReGroupedRequestsReportExcelExport',
  GetReceivedRequestsFromOfficeExcelExport:
    'Report/GetReceivedRequestsFromOfficeExcelExport',
  PendingReceiveFromAnotherOfficeRequestsExcelExport:
    'Report/PendingReceiveFromAnotherOfficeRequestsExcelExport',
  GetAllPendingReceivedItems: 'StoreTransaction/GetAllPendingReceivedItems',
  GetAllReceivedItems: 'StoreTransaction/GetAllReceivedItems',
  GetAllReceivedScheduledItems: 'StoreTransaction/GetAllReceivedScheduledItems',
  GetOperatorsDDL: 'User/GetOperatorsDDL',
  AssignRequest: 'StoreTransaction/AssignRequest',
  ConfirmReceived: 'StoreTransaction/ConfirmReceived',
  SendItemsFromstore: 'StoreTransaction/SendItemsFromstore',
  GetAllReceivedItemsByAssignedUser:
    'StoreTransaction/GetAllReceivedItemsByAssignedUser',
  EditScheduleOutTime: 'StoreTransaction/EditScheduleOutTime',
  GetStoreAssignReasonDropDown: 'Lookup/GetStoreAssignReasonDropDown',
  SaveItemToStore: 'StoreTransaction/SaveItemToStore',
  GetStoreDropDownByOffice: 'Store/GetStoreDropDownByOffice',
  validateAccountNumber: 'PersonalInfo/ValidateAccountNumber',
  AssignGroupToSupervisor: 'Item/AssignGroupToSupervisor',
  ConfirmOfficeManualDelivery: 'Item/ConfirmOfficeManualDelivery',
  GetClientServicePackagingSize:
    'ServicePackagingSize/GetServicePackagingSizeForClientRequest',
  GeUsersPerCurrentOffice: 'User/GeUsersPerCurrentOffice',
  GetIncomingRequests: 'Request/GetIncomingRequests',
  GetOutgoingRequests: 'Request/GetOutgoingRequests',
  UpdatePostOfficeSetting: 'PostOfficeSetting/UpdatePostOfficeSetting',
  UpdateReceiver: 'PushNotificationReceiver/UpdateReceiver',
  RemoveReceiver: 'PushNotificationReceiver/RemoveReceiver',
  GetNotification: 'PushNotification/GetNotification',
  MarkNotificationAsSeen: 'PushNotification/MarkNotificationAsSeen'
};
